filetype plugin on
syntax enable       "Enables syntax highlighting
colorscheme molokai "Sets the colorscheme
set number      	  "Enable line numbering
set shiftwidth=4    "Set tab width after going to new line
"set tabstop=4       "Number of visual spaces per TAB.  commented out due to using expandtab
set softtabstop=4   "Number of space in tab when editing
set expandtab       "Converts TAB to spaces
set showcmd			    "Show command in bottom bar
set cursorline      "Highlights current line
filetype indent on  "Prefer intending scheme of certain languages
set showmatch       "Highlight matching braces, brackets, etc
set incsearch       "Search as characters are entered
set hlsearch        "Highlight search

" Uncomment below for WSL yank support (VIM 8.0+ REQUIRED)
"let s:clip = '/mnt/c/Windows/System32/clip.exe'  " default location
"if executable(s:clip)
"    augroup WSLYank
"        autocmd!
"        autocmd TextYankPost * call system(s:clip, join(v:event.regcontents, "\<CR>"))
"    augroup END
"end
